CREATE TABLE stock (
  id         INTEGER PRIMARY KEY   NOT NULL,
  stock_code CHARACTER VARYING(10) NOT NULL,
  stock_name CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE stock_detail (
  id          INTEGER PRIMARY KEY    NOT NULL,
  stock_id    INTEGER,
  comp_name   CHARACTER VARYING(100) NOT NULL,
  comp_desc   CHARACTER VARYING(255) NOT NULL,
  remark      CHARACTER VARYING(255) NOT NULL,
  listed_date DATE                   NOT NULL,
  FOREIGN KEY (stock_id) REFERENCES stock (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
